### ISSUE TITLE
CAMB parameter file generation not working

### ISSUE THREAD

**Issue by AdGonsi** [apetri/LensTools#18]
When trying to generate the parameter file for CAMB as described in the tutorial I get this error:
Traceback (most recent call last):
  File "/home/run.py", line 33, in <module>
    collection.writeCAMB(z=0.0,settings=camb_settings)
  File "/home/miniconda3/envs/lenstools/lib/python2.7/site-packages/lenstools/pipeline/simulation.py", line 2399, in writeCAMB
    paramfile.write(settings.write(output_root=os.path.join(self.home_subdir,output_root),cosmology=self.cosmology,redshifts=z))
  File "/home/miniconda3/envs/lenstools/lib/python2.7/site-packages/lenstools/simulations/camb.py", line 293, in write
    if cosmology._nmassivenu==0:
AttributeError: 'LensToolsCosmology' object has no attribute '_nmassivenu'

**Comment by warmtoday** [comment]
您的邮件已收到，谢谢！

**Comment by ffriaslago** [comment]
I got the same error and I ended up commenting all the instances of '_nmassivenu' in the camb.py file. After that, it worked, although I got stuck in the job submission

**Comment by warmtoday** [comment]
您的邮件已收到，谢谢！
